---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "2"
    ci.w6d.io/task: deploy
  name: deploy-step-generic
step:
  args:
    - upgrade
    - --install
    - -f
    - $(params.values)
    - $(params.flags[*])
    - --namespace
    - $(params.namespace)
    - --version
    - 1.1.6
    - $(params.release_name)
    - w6dio/app
  command:
    - helm3
  image: w6dio/kubectl:v1.2.1
  name: deploy
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "3"
    ci.w6d.io/task: deploy
  name: deploy-check-step-generic
step:
  args:
    - $(params.release_name)
    - $(params.namespace)
  command:
    - validate_rollout
  image: w6dio/kubectl:v1.2.1
  name: check
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "1"
    ci.w6d.io/task: deploy
  name: deploy-get-values-step-generic
step:
  image: w6dio/s3cmd:v0.1.1
  name: get-values
  script: |
    s3cmd get --skip-existing s3://artifacts/${W6D_PROJECT_ID}/${W6D_PIPELINE_ID}/values.yaml /helm/values/values.yaml
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: trivy-standard
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/task: trivy
    ci.w6d.io/order: "0"
step:
  name: trivy-standard
  image: aquasec/trivy:0.12.0
  script: |
    echo $(params.DOCKER_IMAGE_URL)
    trivy --exit-code 0 --cache-dir .trivycache/ --no-progress -o $(workspaces.artifacts.path)/trivy-report.json $(params.DOCKER_IMAGE_URL)
    trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --severity HIGH $(params.DOCKER_IMAGE_URL)
    trivy --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress $(params.DOCKER_IMAGE_URL)
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "0"
    ci.w6d.io/task: owasp
  name: owasp-deploy-get-values-step-generic
step:
  image: w6dio/s3cmd:v0.1.1
  name: get-values
  script: |
    s3cmd get --skip-existing s3://artifacts/${W6D_PROJECT_ID}/${W6D_PIPELINE_ID}/values.yaml /helm/values/values.yaml
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "1"
    ci.w6d.io/task: owasp
  name: owasp-deploy-step-generic
step:
  image: w6dio/kubectl:v1.1.3
  name: deploy
  script: |
    helm3 repo add w6dio https://charts.w6d.io
    helm3 upgrade --install -f /helm/values/values.yaml --set ingress.enabled=false --set service.name=owasp-${W6D_PIPELINE_ID} --set serviceAccount.name=sa-${W6D_PROJECT_ID}-${W6D_PIPELINE_ID} --version 1.1.6 owasp-${W6D_PIPELINE_ID} w6dio/app
    validate_rollout owasp-${W6D_PIPELINE_ID} p6e-cx-${W6D_PROJECT_ID}
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: owasp-baseline
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "2"
    ci.w6d.io/task: owasp
step:
  image: w6dio/owasp-zap:v0.0.2
  name: owasp-baseline
  script: |
    #!/bin/sh
    zap-baseline.py -t http://owasp-${W6D_PIPELINE_ID}:8080 -J report-baseline.json -d -I
    cp /zap/wrk/report-baseline.json $(workspaces.artifacts.path)
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "5"
    ci.w6d.io/task: owasp
  name: owasp-clean-step-generic
step:
  image: w6dio/kubectl:v1.1.3
  name: clean
  script: |
    helm3 delete owasp-${W6D_PIPELINE_ID}
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: owasp-graphql
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "4"
    ci.w6d.io/task: owasp
step:
  image: w6dio/owasp-zap:v0.0.2
  name: owasp-graphql
  script: |
    #!/bin/sh
    zap-api-scan.py -t http://owasp-${W6D_PIPELINE_ID}:8080 -T 60 -D 30 -f graphql -J report-graphql.json -d -I
    cp /zap/wrk/report-graphql.json $(workspaces.artifacts.path)
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: owasp-fullscan
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "3"
    ci.w6d.io/task: owasp
step:
  image: w6dio/owasp-zap:v0.0.2
  name: owasp-fullscan
  script: |
    #!/bin/sh
    zap-full-scan.py -t http://owasp-${W6D_PIPELINE_ID}:8080 -T 60 -D 30 -J report-fullscan.json -d -I
    cp /zap/wrk/report-fullscan.json $(workspaces.artifacts.path)
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "5"
    ci.w6d.io/task: nmap-nse
  name: nmap-nse-clean-step-generic
  namespace: ci-system
step:
  image: w6dio/kubectl:v1.1.3
  name: clean
  script: |
    helm3 delete nmap-nse-${W6D_PIPELINE_ID}
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "0"
    ci.w6d.io/task: nmap-nse
  name: nmap-nse-deploy-get-values-step-generic
step:
  image: w6dio/s3cmd:v0.1.1
  name: get-values
  script: |
    s3cmd get --skip-existing s3://artifacts/${W6D_PROJECT_ID}/${W6D_PIPELINE_ID}/values.yaml /helm/values/values.yaml
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "1"
    ci.w6d.io/task: nmap-nse
  name: nmap-nse-deploy-step-generic
step:
  image: w6dio/kubectl:v1.1.3
  name: deploy
  script: |
    helm3 repo add w6dio https://charts.w6d.io
    helm3 upgrade --install -f /helm/values/values.yaml --set ingress.enabled=false --set service.name=nmap-nse-${W6D_PIPELINE_ID} --set serviceAccount.name=sa-${W6D_PROJECT_ID}-${W6D_PIPELINE_ID} --version 1.1.6 nmap-nse-${W6D_PIPELINE_ID} w6dio/app
    validate_rollout nmap-nse-${W6D_PIPELINE_ID} p6e-cx-${W6D_PROJECT_ID}
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: nmap-vuln
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/order: "2"
    ci.w6d.io/task: nmap-nse
step:
  image: w6dio/docker-nmap:v0.0.2
  name: nmap-vuln
  script: |
    nmap -Pn -v -A -T5 --script vuln http://nmap-nse-${W6D_PIPELINE_ID}:8080 -p 8080  -oX $(workspaces.artifacts.path)
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: nmap-vulners
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/task: nmap-nse
    ci.w6d.io/order: "4"
params:
  - name: TARGET_PATHS
    description: define by client  all path targeted exemple '{"/","api/v1"}'
    type: string
step:
  name: nmap-vulners
  image: "instrumentisto/nmap"
  script: |
    nmap -Pn -v -A -T5 -p 8080 --script $(resources.inputs.source.path)/vulnersCom_nmapvulner/http-vulners-regex.nse --script-args paths={$(params.TARGET_PATHS)} http://nmap-nse-${W6D_PIPELINE_ID} -oX $(workspaces.artifacts.path)/reportCVE-http-vulners-regex.xml
    nmap -Pn -v -A -T5 --script $(resources.inputs.source.path)/scipag_vulscan/vulners.nse --script-args mincvss=5.0 http://nmap-nse-${W6D_PIPELINE_ID} -oX $(workspaces.artifacts.path)/reportCVE-vulners.xml
---
apiVersion: ci.w6d.io/v1alpha1
kind: Step
metadata:
  name: nmap-vulscan
  annotations:
    ci.w6d.io/kind: generic
    ci.w6d.io/task: nmap-nse
    ci.w6d.io/order: "3"
step:
  name: nmap-vulscan
  image: "instrumentisto/nmap"
  script: |
    nmap -Pn -v -A -T5 --script scipag_vulscan/vulscan.nse http://nmap-nse-${W6D_PIPELINE_ID} -p 8080 -oX $(workspaces.artifacts.path)/reportCVE-vulscan.xml
---
