[[rules]]
	description = "entropy"
	regex = '''['|"]([0-9a-zA-Z-._{}$\/\+=]{20,120})['|"]'''
	tags = ["entropy"]
        [[rules.Entropies]]
            Min = "3.3"
            Max = "3.5"
            Group = "1"

