title = "AWS Enumeration"

[[regexes]]
description = "AWS Secrets"
regex = '''AKIA[0-9A-Z]{16}'''

[[regexes]]
description = "AWS ARN"
regex = '''arn:aws:.*'''

[[regexes]]
description = "AWS EC2 Internal"
regex = '''.*\.compute\.internal'''

[[regexes]]
description = "AWS EC2 External 001"
regex = '''ec2-.+?\.compute\.amazonaws\.com'''

[[regexes]]
description = "AWS EC2 External 002"
regex = '''ec2-.+?\.compute-1\.amazonaws\.com'''

[[regexes]]
description = "AWS ELB 001"
regex = '''.*\.elb\.amazonaws\.com'''

[[regexes]]
description = "AWS ELB 002"
regex = '''.*\.elb\..+?\.amazonaws\.com'''

[[regexes]]
description = "AWS RDS"
regex = '''.*\.rds\.amazonaws\.com'''

[[regexes]]
description = "AWS ElasticCache"
regex = '''.*\.cache\.amazonaws\.com'''

[[regexes]]
description = "AWS S3 Endpoint 001"
regex = '''.*\.s3\.amazonaws\.com'''

[[regexes]]
description = "AWS S3 Endpoint 002"
regex = '''.*\.s3-website.+?\.amazonaws\.com'''

[[regexes]]
description = "AWS S3 Bucket"
regex = '''s3://[a-z0-9-.]+'''

[[regexes]]
description = "AWS CloudFront"
regex = '''.*\.cloudfront\.net'''

[[regexes]]
description = "AWS API Gateway"
regex = '''execute-api\..+?\.amazonaws\.com'''
